apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: clickhouse-vmservicescrape
spec:
  endpoints:
    - port: signoz-clickhouse-operator-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: clickhouse
