apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: signoz-otel-collector-route
  namespace: envoy-gateway
spec:
  parentRefs:
    - name: eg
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: signoz-otel-collector
          port: 4318
          weight: 1
      matches:
        - path:
            type: Exact
            # value: /telemetry/v1/traces
            value: /v1/traces
        - path:
            type: Exact
            value: /telemetry/v1/metrics
        - path:
            type: Exact
            value: /telemetry/v1/logs
      # filters:
      #   - type: URLRewrite
      #     urlRewrite:
      #       path:
      #         type: ReplacePrefixMatch
      #         replacePrefixMatch: /
